sonar.issue.ignore.multicriteria=r1,r2,r3

# Make sure use of "sprintf" function is safe here or replace it with a call to "snprintf"
sonar.issue.ignore.multicriteria.r1.ruleKey=c:S6069
sonar.issue.ignore.multicriteria.r1.resourceKey=**/*

# Make sure use of "strlen" is safe here
sonar.issue.ignore.multicriteria.r2.ruleKey=c:S5813
sonar.issue.ignore.multicriteria.r2.resourceKey=**/*

# Make sure use of "strcpy" is safe here
sonar.issue.ignore.multicriteria.r3.ruleKey=c:S5801
sonar.issue.ignore.multicriteria.r3.resourceKey=**/*