COMPONENT_SUBMODULES += lib/cAT
COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_PRIV_INCLUDEDIRS := src lib/cAT/src
COMPONENT_SRCDIRS := src lib/cAT/src
COMPONENT_EMBED_FILES += web-gz/index.html
COMPONENT_EMBED_FILES += web-gz/settings.html
COMPONENT_EMBED_FILES += web-gz/management.html
COMPONENT_EMBED_FILES += web-gz/about.html
COMPONENT_EMBED_FILES += web-gz/bootstrap.min.css
COMPONENT_EMBED_FILES += web-gz/bootstrap.bundle.min.js
COMPONENT_EMBED_FILES += web-gz/favicon.ico
COMPONENT_EMBED_FILES += server_certs/ca_cert.pem