# yaml-language-server: $schema=https://github.com/dzurikmiroslav/esp32-evse/raw/refs/heads/master/board-config/board-config-schema-1.json

deviceName: ESP32-S2 minimal EVSE

buttonGpio: 0

pilot:
  gpio: 6
  adcChannel: 3
  levels: [2410, 2104, 1797, 1491, 265]

acRelayGpios: [5]

serials:
  - type: uart
    name: UART via USB
    rxdGpio: 44
    txdGpio: 43

otaChannels:
  - name: stable
    path: https://dzurikmiroslav.github.io/esp32-evse/ota/stable/esp32s2.json