name: Build

on:
  push:
    tags-ignore:
     - '**'
    branches:
      - '**'
  pull_request:
  workflow_call:
    outputs:
      app_version:
        description: "App version"
        app_version: ${{ jobs.build.outputs.app_version }}

jobs:
  env:
    uses: ./.github/workflows/env.yaml

  build:
    name: Build for all platforms
    runs-on: ubuntu-latest
    needs: env
    outputs:
      app_version: ${{ steps.app_version.outputs.app_version }}
    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: App version
        id: app_version
        run: |
          VERSION=$(git describe --always --tags --dirty)
          echo "app_version=$VERSION >> $GITHUB_OUTPUT

      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ needs.env.outputs.esp_idf_version }}
          target: ${{ matrix.platform }}

      - name: Merge factory
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ needs.env.outputs.esp_idf_version }}
          target: ${{ matrix.platform }}
          command: esptool.py --chip ${{ matrix.platform }} merge_bin -o build/${{ matrix.platform }}-evse.factory.bin --flash_mode dio --flash_freq 40m --flash_size 4MB \
            0x1000 build/bootloader/bootloader.bin \
            0x10000 build/esp32-evse.bin \
            0x8000 build/partition_table/partition-table.bin \
            0xd000 build/ota_data_initial.bin

      - name: Rename file ota
        shell: bash
        run: cp build/esp32-evse.bin ${{ matrix.platform }}-evse.ota.bin
      
      - name: Upload artifact ota
        uses: actions/upload-artifact@v4
        with:
          name: ota-${{ matrix.platform }}
          path: ${{ matrix.platform }}-evse.ota.bin

      - name: Upload artifact factory
        uses: actions/upload-artifact@v4
        with:
          name: factory-${{ matrix.platform }}
          path: build/${{ matrix.platform }}-evse.factory.bin

      - name: Upload release assets ota
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.platform }}-evse.ota.bin
          asset_name: ${{ matrix.platform }}-evse.ota.bin
          asset_content_type: application/octet-stream

      - name: Upload release assets factory
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/${{ matrix.platform }}-evse.factory.bin
          asset_name: ${{ matrix.platform }}-evse.factory.bin
          asset_content_type: application/octet-stream