name: Build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  env:
    uses: ./.github/workflows/env.yaml

  build:
    name: Build for all platforms
    runs-on: ubuntu-latest
    needs: env

    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ needs.env.outputs.esp_idf_version }}
          target: ${{ matrix.platform }}

      - name: Rename file 
        shell: bash
        run: cp build/esp32-evse.bin ${{ matrix.platform }}-evse.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.platform }}
          path: ${{ matrix.platform }}-evse.bin
