name: Build

# env:
#   ESP_IDF_VERSION: v5.3

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build for all platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]

    steps:
      - name: Set environment variables
        run: sh .github/env.sh

      - name: Checkout
        uses: actions/checkout@v4
   
      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: $ESP_IDF_VERSION
          target: ${{ matrix.platform }}

      - name: Rename file 
        shell: bash
        run: cp build/esp32-evse.bin ${{ matrix.platform }}-evse.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.platform }}
          path: ${{ matrix.platform }}-evse.bin
