name: Publish bleeding edge

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        description: 'Select channel'
        required: true
        default: bleeding-edge
        options:
          - bleeding-edge
          - testing
          - stable

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout GitHub Pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
    
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: tmp

      - name: Write
        run: |
            export VERSION=$(git describe --always --tags --dirty)
            for file in ota/bleeding-edge/*.json; do
              cat $file | jq ".version = \"$VERSION\"" | tee $file
            done
            mv tmp/ota-*/*-evse.ota.bin ota/bleeding-edge/
            rm -rf tmp

      - name: Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git status

          git add .
          git commit -m "Publish bleeding-edge version $VERSION"
          git push
