name: Publish OTA

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        description: 'Select channel'
        required: true
        default: bleeding-edge
        options:
          - bleeding-edge
          - testing
          - stable

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
    
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: tmp
      - name: log
        run: echo "app_version=${{ needs.build.outputs.app_version }}"

      - name: Write
        run: |
            for file in ota/$channel/*.json; do
              cat $file | jq ".version = \"${{ needs.build.outputs.app_version }}\"" | tee $file
            done
            mv tmp/ota-*/*-evse.ota.bin ota/$channel/
            rm -rf tmp

      - name: Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git status
          git commit -m "Publish $channel version $VERSION"
          git push
