name: Publish stable

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string

jobs:
  publish:
    name: Publish stable
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout GitHub Pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download artifacts
        run: gh release download ${{ inputs.tag }} --dir ota/stable --pattern '*.ota.bin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: check
        run: ls -al ota/stable


