name: Build release

on:
  release:
    types: [created]

jobs:
  env:
    uses: ./.github/workflows/env.yaml

  firmware:
    name: Build release for all platforms
    runs-on: ubuntu-latest
    needs: env
    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ needs.env.outputs.esp_idf_version }}
          target: ${{ matrix.platform }}

      - name: Merge factory
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ needs.env.outputs.esp_idf_version }}
          target: ${{ matrix.platform }}
          command: esptool.py --chip ${{ matrix.platform }} merge_bin -o build/${{ matrix.platform }}-evse.factory.bin --flash_mode dio --flash_freq 40m --flash_size 4MB \
            0x1000 build/bootloader/bootloader.bin \
            0x10000 build/esp32-evse.bin \
            0x8000 build/partition_table/partition-table.bin \
            0xd000 build/ota_data_initial.bin

      - name: Rename file bin
        shell: bash
        run: cp build/esp32-evse.bin ${{ matrix.platform }}-evse.bin
      
      - name: Upload release bin asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.platform }}-evse.bin
          asset_name: ${{ matrix.platform }}-evse.bin
          asset_content_type: application/octet-stream
  
      - name: Upload release factory asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/${{ matrix.platform }}-evse.factory.bin
          asset_name: ${{ matrix.platform }}-evse.factory.bin
          asset_content_type: application/octet-stream