name: Build release

on:
  release:
    types: [created]

jobs:
  env:
    uses: ./.github/workflows/env.yaml

  firmware:
    name: Build release for all platforms
    runs-on: ubuntu-latest
    needs: env
    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
   
      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ needs.env.outputs.esp_idf_version }}
          target: ${{ matrix.platform }}

      - name: Rename file 
        shell: bash
        run: cp build/esp32-evse.bin ${{ matrix.platform }}-evse.bin

      - name: Upload release assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.platform }}-evse.bin
          asset_name: ${{ matrix.platform }}-evse.bin
          asset_content_type: application/octet-stream

  factory:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - platform: esp32
            board: esp32devkitc
          - platform: esp32s2
            board: esp32s2da
          - platform: esp32
            board: esp32minimal
          - platform: esp32s2
            board: esp32s2minimal
          - platform: esp32s3
            board: esp32s3minimal
    steps:
      - name: Checkout
        uses: actions/checkout@v4
   
      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ needs.env.outputs.esp_idf_version }}
          target: ${{ matrix.platform }}
          command: export SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.${{ matrix.board }}"; idf.py build

      - name: Merge
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ needs.env.outputs.esp_idf_version }}
          target: ${{ matrix.platform }}
          command: esptool.py --chip ${{ matrix.platform }} merge_bin -o build/${{ matrix.board }}.bin --flash_mode dio --flash_freq 40m --flash_size 4MB \
            0x1000 build/bootloader/bootloader.bin \
            0x10000 build/esp32-evse.bin \
            0x8000 build/partition_table/partition-table.bin \
            0xd000 build/ota_data_initial.bin \
            0x3b0000 build/cfg.bin

      - name: Upload release assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/${{ matrix.board }}.bin
          asset_name: ${{ matrix.board }}.bin
          asset_content_type: application/octet-stream
