name: Reusable Workflow to Set Environment Variables

env:
  ESP_IDF_VERSION: v5.3

on:
  workflow_call:

jobs:
  set-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
            echo "ESP_IDF_VERSION=$ESP_IDF_VERSION" >> $GITHUB_ENV